---
# Simple MySQL Playbook
# MySQL by root, and then have its rights adjusted.
- hosts: do
  user: root
  sudo: false
  gather_facts: no

  vars:
    mysql_root_password: "test"
    # workers: use at template ansible_processor_count
    connections: "1024"
    is_10_up: "'$ansible_distribution_version' >= '10.04'"
    is_ubuntu: "'$ansible_distribution' == 'Ubuntu'"

  tasks:
    - include: mysql/tasks/setup.yml

  handlers:
    - name: restart mysqld
      action: service name=mysqld state=restarted
