---
# Simple Ubuntu Nginx playbook
# Nginx needs to be installed by a poweruser, then have rights adjusted.
- hosts: do
  user: root
  sudo: false

  vars:
    # workers: use at template ansible_processor_count
    connections: "1024"
    is_10_up: "'$ansible_distribution_version' >= '10.04'"
    is_ubuntu: "'$ansible_distribution' == 'Ubuntu'"

  tasks:
    - include: nginx/tasks/setup.yml

  handlers:
    - name: restasrt nginx
      action: service name=nginx state=restarted

